/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const GalleryAddImageResponse = IDL.Record({
  'id' : IDL.Text,
  'blob' : IDL.Opt(ExternalBlob),
  'message' : IDL.Opt(IDL.Text),
  'success' : IDL.Bool,
});
export const Category = IDL.Variant({
  'performance' : IDL.Null,
  'aesthetics' : IDL.Null,
});
export const Time = IDL.Int;
export const Habit = IDL.Record({
  'id' : IDL.Text,
  'effectiveness' : IDL.Int,
  'isCritical' : IDL.Bool,
  'ease' : IDL.Int,
  'name' : IDL.Text,
  'createdAt' : Time,
  'affordability' : IDL.Int,
  'anecdotes' : IDL.Text,
  'description' : IDL.Text,
  'totalScore' : IDL.Int,
  'updatedAt' : Time,
  'category' : Category,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addGalleryImage' : IDL.Func(
      [IDL.Text, ExternalBlob],
      [GalleryAddImageResponse],
      [],
    ),
  'addHabit' : IDL.Func(
      [
        IDL.Text,
        Category,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Int,
        IDL.Int,
        IDL.Text,
        IDL.Bool,
      ],
      [Habit],
      [],
    ),
  'deleteHabit' : IDL.Func([IDL.Text], [], []),
  'editHabit' : IDL.Func(
      [
        IDL.Text,
        Category,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Int,
        IDL.Int,
        IDL.Text,
        IDL.Bool,
      ],
      [Habit],
      [],
    ),
  'getAllHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
  'getGalleryImage' : IDL.Func([IDL.Text], [ExternalBlob], ['query']),
  'getGalleryImages' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, ExternalBlob))],
      ['query'],
    ),
  'getHabit' : IDL.Func([IDL.Text], [Habit], ['query']),
  'getHabitsByCategory' : IDL.Func([Category], [IDL.Vec(Habit)], ['query']),
  'getHeaderTitle' : IDL.Func([], [IDL.Text], ['query']),
  'removeGalleryImage' : IDL.Func([IDL.Text], [], []),
  'updateHeaderTitle' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const GalleryAddImageResponse = IDL.Record({
    'id' : IDL.Text,
    'blob' : IDL.Opt(ExternalBlob),
    'message' : IDL.Opt(IDL.Text),
    'success' : IDL.Bool,
  });
  const Category = IDL.Variant({
    'performance' : IDL.Null,
    'aesthetics' : IDL.Null,
  });
  const Time = IDL.Int;
  const Habit = IDL.Record({
    'id' : IDL.Text,
    'effectiveness' : IDL.Int,
    'isCritical' : IDL.Bool,
    'ease' : IDL.Int,
    'name' : IDL.Text,
    'createdAt' : Time,
    'affordability' : IDL.Int,
    'anecdotes' : IDL.Text,
    'description' : IDL.Text,
    'totalScore' : IDL.Int,
    'updatedAt' : Time,
    'category' : Category,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addGalleryImage' : IDL.Func(
        [IDL.Text, ExternalBlob],
        [GalleryAddImageResponse],
        [],
      ),
    'addHabit' : IDL.Func(
        [
          IDL.Text,
          Category,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Int,
          IDL.Int,
          IDL.Text,
          IDL.Bool,
        ],
        [Habit],
        [],
      ),
    'deleteHabit' : IDL.Func([IDL.Text], [], []),
    'editHabit' : IDL.Func(
        [
          IDL.Text,
          Category,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Int,
          IDL.Int,
          IDL.Text,
          IDL.Bool,
        ],
        [Habit],
        [],
      ),
    'getAllHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
    'getGalleryImage' : IDL.Func([IDL.Text], [ExternalBlob], ['query']),
    'getGalleryImages' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, ExternalBlob))],
        ['query'],
      ),
    'getHabit' : IDL.Func([IDL.Text], [Habit], ['query']),
    'getHabitsByCategory' : IDL.Func([Category], [IDL.Vec(Habit)], ['query']),
    'getHeaderTitle' : IDL.Func([], [IDL.Text], ['query']),
    'removeGalleryImage' : IDL.Func([IDL.Text], [], []),
    'updateHeaderTitle' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };